# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #E2DEDC
background         #292829
cursor             #8A8788

active_tab_foreground     #292829
active_tab_background     #E2DEDC
inactive_tab_foreground   #E2DEDC
inactive_tab_background   #292829

active_border_color   #E2DEDC
inactive_border_color #292829
bell_border_color     #1F1E22

color0      #4E4E4F
color1		#1F1E22
color2		#252427
color3		#504B4B
color4		#575050
color5		#7C7370
color6		#827975
color7		#CEC8C5
color8		#908C8A
color9		#29282D
color10		#313034
color11		#6B6464
color12		#746A6B
color13		#A59995
color14		#ADA19C
color15		#CEC8C5
